In [125]:
import pandas as pd 
import numpy as np

In [126]:
# 1. Load the Data .........................................................................

In [127]:
all_seet = pd.read_excel('Other Data.xlsx', sheet_name=None)

Food_Details = all_seet['Food_Details']
Customer_Details = all_seet['Customer Details']
Resturant_Details = all_seet['Resturant_Details']

In [128]:
# 2. Inspect the Data ...............................................................

In [129]:
Food_Details.head()

   ItemCode       Food Name    Food_Type
0      2142  Butter Chicken  Main Course
1      2152    Palak Paneer  Main Course
2      2145   Chole Bhature  Main Course
3      2149         Biryani  Main Course
4      2141     Masala Dosa    Breakfast

In [130]:
Food_Details.shape

(23, 3)

In [131]:
Food_Details.columns

Index(['ItemCode', 'Food Name', 'Food_Type'], dtype='str')

In [132]:
Food_Details.info()

<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ItemCode   23 non-null     int64
 1   Food Name  23 non-null     str
 2   Food_Type  23 non-null     str
dtypes: int64(1), str(2)
memory usage: 684.0 bytes

In [133]:
Customer_Details.head()

   customer_id  customer_name member_Type
0            1      Sai Naidu        Gold
1            2  Krishna Menon           G
2            3     Uday Menon        Gold
3            4   Kartik Patel        Gold
4            5   Shaurya Jain     Regular

In [134]:
Customer_Details.shape

(30, 3)

In [135]:
Customer_Details.columns

Index(['customer_id', 'customer_name', 'member_Type'], dtype='str')

In [136]:
Customer_Details.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    30 non-null     int64
 1   customer_name  30 non-null     str
 2   member_Type    30 non-null     str
dtypes: int64(1), str(2)
memory usage: 852.0 bytes

In [137]:
Resturant_Details.head()

   Resturant_Code   Resturant_Name Resturant_type
0             212          Bukhara   North Indian
1             213        Karavalli        Mughlai
2             211  Saravana Bhavan   North Indian
3             216       Moti Mahal        Mughlai
4             217          Dakshin   South Indian

In [138]:
Resturant_Details.shape

(6, 3)

In [139]:
Resturant_Details.columns

Index(['Resturant_Code', 'Resturant_Name', 'Resturant_type'], dtype='str')

In [140]:
Resturant_Details.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Resturant_Code  6 non-null      int64
 1   Resturant_Name  6 non-null      str
 2   Resturant_type  6 non-null      str
dtypes: int64(1), str(2)
memory usage: 276.0 bytes

In [141]:
# 3. Clean the member_Type Column in Customer Details ......................................................................

In [142]:
Customer_Details.columns

Index(['customer_id', 'customer_name', 'member_Type'], dtype='str')

In [143]:
Customer_Details['member_Type'].unique()

<StringArray>
['Gold', 'G', 'Regular', 'R']
Length: 4, dtype: str

In [144]:
Customer_Details['member_Type'] = Customer_Details['member_Type'].replace({
    'G': 'Gold', 
    'R': 'Regular'
})

In [145]:
Customer_Details['member_Type'].unique()

<StringArray>
['Gold', 'Regular']
Length: 2, dtype: str

In [146]:
# 4. Analyse Customer Membership ....................................................................

In [147]:
Customer_Details.groupby('member_Type').count()

             customer_id  customer_name
member_Type
Gold                  20             20
Regular               10             10

In [148]:
# 5. Extract First Names from Customer Names .............................................................................

In [149]:
Customer_Details.head()

   customer_id  customer_name member_Type
0            1      Sai Naidu        Gold
1            2  Krishna Menon        Gold
2            3     Uday Menon        Gold
3            4   Kartik Patel        Gold
4            5   Shaurya Jain     Regular

In [150]:
Customer_Details['First_name'] = Customer_Details['customer_name'].str.split().str[0]

In [151]:
Customer_Details.head()

   customer_id  customer_name member_Type First_name
0            1      Sai Naidu        Gold        Sai
1            2  Krishna Menon        Gold    Krishna
2            3     Uday Menon        Gold       Uday
3            4   Kartik Patel        Gold     Kartik
4            5   Shaurya Jain     Regular    Shaurya

In [152]:
# 6. Filter Customers by Name Pattern ....................................................................................

In [153]:
# Starts with A
starts_A = Customer_Details[
    Customer_Details['customer_name'].str.contains(r'^A', case=False, na=False)
]

# Ends with n
ends_n = Customer_Details[
    Customer_Details['customer_name'].str.contains(r'n$', case=False, na=False)
]

print(starts_A)
print(ends_n)

    customer_id    customer_name member_Type First_name
6             7      Aditya Iyer     Regular     Aditya
8             9      Ashok Naidu     Regular      Ashok
10           11     Arjun Mishra     Regular      Arjun
11           12      Aniket Shah     Regular     Aniket
17           18       Arnav Iyer        Gold      Arnav
18           19      Aarav Gupta        Gold      Aarav
19           20  Atharv Malhotra        Gold     Atharv
21           22  Ayaan Choudhary        Gold      Ayaan
23           24      Alok Kapoor        Gold       Alok
   customer_id  customer_name member_Type First_name
1            2  Krishna Menon        Gold    Krishna
2            3     Uday Menon        Gold       Uday
4            5   Shaurya Jain     Regular    Shaurya
9           10     Parth Jain        Gold      Parth

In [154]:
# 7. Analyse Food Items by Type ............................................................................................

In [155]:
Food_Details.head()

   ItemCode       Food Name    Food_Type
0      2142  Butter Chicken  Main Course
1      2152    Palak Paneer  Main Course
2      2145   Chole Bhature  Main Course
3      2149         Biryani  Main Course
4      2141     Masala Dosa    Breakfast

In [156]:
Food_Details.groupby('Food_Type').count().sort_values('Food Name', ascending=False)

             ItemCode  Food Name
Food_Type
Main Course        11         11
Snack               5          5
Dessert             3          3
Breakfast           2          2
Beverage            1          1
Appetizer           1          1

In [157]:
# 8. Filter Food Items by Conditions

In [158]:
Food_Details.columns

Index(['ItemCode', 'Food Name', 'Food_Type'], dtype='str')

In [159]:
# List all Main Course items that have an ItemCode greater than 2150.
Food_Details[
    (Food_Details['Food_Type'] == 'Main Course') & (Food_Details['ItemCode'] > 2150)
]

    ItemCode         Food Name    Food_Type
1       2152      Palak Paneer  Main Course
6       2161        Rogan Josh  Main Course
10      2165  Tandoori Chicken  Main Course
11      2163             Rajma  Main Course
18      2167       Kofta Curry  Main Course
20      2151       Malai Kofta  Main Course
22      2162     Bhindi Masala  Main Course

In [160]:
# List all Snack items that are not Pav Bhaji.
Food_Details[
    (Food_Details['Food_Type'] != 'pav Bhaji')
]

    ItemCode         Food Name    Food_Type
0       2142    Butter Chicken  Main Course
1       2152      Palak Paneer  Main Course
2       2145     Chole Bhature  Main Course
3       2149           Biryani  Main Course
4       2141       Masala Dosa    Breakfast
5       2147            Samosa        Snack
6       2161        Rogan Josh  Main Course
7       2148         Dal Tadka  Main Course
8       2150         Pav Bhaji        Snack
9       2144      Aloo Paratha    Breakfast
10      2165  Tandoori Chicken  Main Course
11      2163             Rajma  Main Course
12      2143         Pani Puri        Snack
13      2155       Gulab Jamun      Dessert
14      2154         Ras Malai      Dessert
15      2164          Vada Pav        Snack
16      2166      Paneer Tikka    Appetizer
17      2160             Lassi     Beverage
18      2167       Kofta Curry  Main Course
19      2146            Dhokla        Snack
20      2151       Malai Kofta  Main Course
21      2153             Kheer      Dessert
22      2162     Bhindi Masala  Main Course

In [161]:
# 9. Categorise Food as Vegetarian or Non‑Vegetarian
# Create a new column Veg_Status with values 'Veg' or 'Non‑Veg' based on the following known non‑veg items:
# Butter Chicken, Rogan Josh, Tandoori Chicken, Biryani (you may add more).

In [162]:
Food_Details.head()

   ItemCode       Food Name    Food_Type
0      2142  Butter Chicken  Main Course
1      2152    Palak Paneer  Main Course
2      2145   Chole Bhature  Main Course
3      2149         Biryani  Main Course
4      2141     Masala Dosa    Breakfast

In [163]:
Food_Details['Food Name'].unique()

<StringArray>
[  'Butter Chicken',     'Palak Paneer',    'Chole Bhature',
          'Biryani',      'Masala Dosa',           'Samosa',
       'Rogan Josh',        'Dal Tadka',        'Pav Bhaji',
     'Aloo Paratha', 'Tandoori Chicken',            'Rajma',
        'Pani Puri',      'Gulab Jamun',        'Ras Malai',
         'Vada Pav',     'Paneer Tikka',            'Lassi',
      'Kofta Curry',           'Dhokla',      'Malai Kofta',
            'Kheer',    'Bhindi Masala']
Length: 23, dtype: str

In [166]:
veg_items = [
    'Palak Paneer',
    'Chole Bhature',
    'Masala Dosa',
    'Samosa',
    'Dal Tadka',
    'Pav Bhaji',
    'Aloo Paratha',
    'Rajma',
    'Pani Puri',
    'Gulab Jamun',
    'Ras Malai',
    'Vada Pav',
    'Paneer Tikka',
    'Lassi',
    'Kheer',
    'Dhokla',
    'Malai Kofta',
    'Bhindi Masala'
]

In [167]:
Food_Details['Veg'] = np.where(Food_Details['Food Name'].isin(veg_items),'Veg','Non-Veg')

In [168]:
Food_Details.head()

   ItemCode       Food Name    Food_Type      Veg
0      2142  Butter Chicken  Main Course  Non-Veg
1      2152    Palak Paneer  Main Course      Veg
2      2145   Chole Bhature  Main Course      Veg
3      2149         Biryani  Main Course  Non-Veg
4      2141     Masala Dosa    Breakfast      Veg

In [169]:
# 10. Groupby with Multiple Aggregations
# On the Food Details DataFrame:
# Group by Food_Type and calculate:
# The number of items (count)
# The minimum, maximum, and average ItemCode
# Use .groupby().agg() with a dictionary.

In [174]:
Food_Details.columns

Index(['ItemCode', 'Food Name', 'Food_Type', 'Veg'], dtype='str')

In [178]:
Food_Details.groupby('Food_Type').agg({
    'ItemCode': ['count', 'min', 'max', 'mean']
})

            ItemCode
               count   min   max    mean
Food_Type
Appetizer          1  2166  2166  2166.0
Beverage           1  2160  2160  2160.0
Breakfast          2  2141  2144  2142.5
Dessert            3  2153  2155  2154.0
Main Course       11  2142  2167  2155.0
Snack              5  2143  2164  2150.0

In [ ]:
# 11. Sort Restaurants
# Sort the restaurant DataFrame by Resturant_Code in descending order.
# Then sort by Resturant_type alphabetically (ascending) and, within each type, by Resturant_Name

In [192]:
Resturant_Details.columns

Index(['Resturant_Code', 'Resturant_Name', 'Resturant_type'], dtype='str')

In [193]:
Resturant_Details.sort_values(
    by=['Resturant_Code', 'Resturant_Name', 'Resturant_type'],
    ascending=[False, True, True]
)

   Resturant_Code   Resturant_Name Resturant_type
4             217          Dakshin   South Indian
3             216       Moti Mahal        Mughlai
5             214    Indian Accent   South Indian
1             213        Karavalli        Mughlai
0             212          Bukhara   North Indian
2             211  Saravana Bhavan   North Indian

In [199]:
# 12. Analyse Restaurant Types
# Count how many restaurants belong to each Resturant_type.
# Which type has the most restaurants?

In [200]:
Resturant_Details.groupby('Resturant_type').count()

                Resturant_Code  Resturant_Name
Resturant_type
Mughlai                      2               2
North Indian                 2               2
South Indian                 2               2

In [202]:
# 13. Handle Duplicates
# Check for duplicate rows in each DataFrame.
# If any exist, remove them (in this file there are none, but practice the code)

In [203]:
Resturant_Details.duplicated().sum()

np.int64(0)

In [204]:
Customer_Details.duplicated().sum()

np.int64(0)

In [205]:
Food_Details.duplicated().sum()

np.int64(0)

In [206]:
# 14. Rename Columns
# Rename all columns in the Restaurant sheet to lower case (e.g., resturant_code, resturant_name, resturant_type).

In [210]:
Resturant_Details.columns = Resturant_Details.columns.str.lower()

In [211]:
Resturant_Details.head()

   resturant_code   resturant_name resturant_type
0             212          Bukhara   North Indian
1             213        Karavalli        Mughlai
2             211  Saravana Bhavan   North Indian
3             216       Moti Mahal        Mughlai
4             217          Dakshin   South Indian