In [2]:
import pandas as pd 
import numpy as np

In [15]:
df = pd.read_csv('customer_churn_dataset_5000.csv')

In [16]:
df.head()

,CustomerID,Gender,Age,SeniorCitizen,TenureMonths,MonthlyCharges,TotalCharges,ContractType,InternetService,PaymentMethod,SupportTickets,SatisfactionScore,Churn
0,CUST100000,Female,61,1,51,89,4450.58,Month-to-month,Fiber,UPI,4,2,1
1,CUST100001,Male,23,0,14,123,1797.51,Month-to-month,DSL,UPI,3,4,0
2,CUST100002,Female,59,0,71,72,5109.13,One year,NaN,Credit Card,0,3,0
3,CUST100003,Male,42,0,60,191,11513.12,Two year,Fiber,Bank Transfer,1,5,0
4,CUST100004,Male,72,1,20,138,2716.03,Month-to-month,DSL,Bank Transfer,1,2,0

In [25]:
df.loc[ 0 : 10 , ['Gender', 'Age']]

    Gender  Age
0   Female   61
1     Male   23
2   Female   59
3     Male   42
4     Male   72
5     Male   74
6     Male   38
7   Female   72
8     Male   33
9   Female   48
10    Male   31

In [23]:
df.iloc[ : , 1 : 3]

      Gender  Age
0     Female   61
1       Male   23
2     Female   59
3       Male   42
4       Male   72
...      ...  ...
4995    Male   46
4996    Male   35
4997  Female   64
4998  Female   55
4999    Male   56

[5000 rows x 2 columns]

In [26]:
# 6. How do you filter rows?

In [29]:
df[df['Gender'] == 'Male']

,CustomerID,Gender,Age,SeniorCitizen,TenureMonths,MonthlyCharges,TotalCharges,ContractType,InternetService,PaymentMethod,SupportTickets,SatisfactionScore,Churn
1,CUST100001,Male,23,0,14,123,1797.51,Month-to-month,DSL,UPI,3,4,0
3,CUST100003,Male,42,0,60,191,11513.12,Two year,Fiber,Bank Transfer,1,5,0
4,CUST100004,Male,72,1,20,138,2716.03,Month-to-month,DSL,Bank Transfer,1,2,0
5,CUST100005,Male,74,1,23,93,2113.85,Two year,Fiber,Cash,1,3,0
6,CUST100006,Male,38,0,2,73,175.38,Month-to-month,DSL,Credit Card,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4991,CUST104991,Male,48,0,36,66,2360.44,Two year,DSL,Bank Transfer,1,2,0
4992,CUST104992,Male,61,1,57,33,1878.31,Month-to-month,NaN,Cash,1,5,0
4995,CUST104995,Male,46,0,10,176,1784.67,Month-to-month,Fiber,UPI,1,1,1
4996,CUST104996,Male,35,0,67,194,13073.42,Two year,DSL,UPI,0,3,0
4999,CUST104999,Male,56,0,65,110,7097.89,Month-to-month,Fiber,Cash,3,1,0